mysqldb:
  image: mysql
  environment:
    MYSQL_DATABASE: alchemytec
    MYSQL_USER: alchemytec
    MYSQL_PASSWORD: alchemytec
    MYSQL_ROOT_PASSWORD: root
springboot:
  image: alchemytec/alchemytec-test
  environment:
    spring.datasource.url: jdbc:mysql://db/alchemytec
  links:
    - mysqldb:db
  ports:
    - 8080:8080

